### ISSUE TITLE
Variable topic length

### ISSUE THREAD

**Issue by msplr** [cvra/msgbus#1]
At the moment there is no information on the topic size. This makes the use of topics with variable length quite difficult.

How about returning the size from `messagebus_topic_read()` and `messagebus_topic_wait()`?

**Comment by SyrianSpock** [comment]
Except the topic doesn't store the size of the message. So you would need to store it in additional field.

**Comment by antoinealb** [comment]
As I see the message bus it is not concerned with encoding: its only role is to pass buffers around. I think variable length handling should end in the encoding layer.
